# Generated by Django 3.0.5 on 2024-12-12 16:08

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_finance', '0033_auto_20241212_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('exception_type', models.CharField(db_index=True, max_length=255)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField()),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('status_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
